### ISSUE TITLE
Json parsing error

### ISSUE THREAD

**Issue by romasilimcano** [howardjohn/scala-server-lambda#4]
Hi,

I am trying to use the library to frontend a http4s server via lambda. I am testing my application using sam local. When I am trying to invoke the application. I am get the following parsing exception. I do not know if the issue is mainly due to sam local. 

java.lang.RuntimeException: An error occurred during JSON parsing
Caused by: java.io.UncheckedIOException: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class io.github.howardjohn.lambda.ProxyEncoding$ProxyRequest]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: lambdainternal.util.NativeMemoryAsInputStream@df27fae; line: 1, column: 2]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class io.github.howardjohn.lambda.ProxyEncoding$ProxyRequest]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: lambdainternal.util.NativeMemoryAsInputStream@df27fae; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1106)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1511)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)

**Comment by howardjohn** [comment]
The Lambda function will accept a [ProxyRequest](https://github.com/howardjohn/scala-server-lambda/blob/master/common/src/main/scala/io/github/howardjohn/lambda/ProxyEncoding.scala) which is the format that API Gateway will send requests with proxy integration enabled. If requests aren't sent through API Gateway, they would need to manually be formatted to include httpMethod, headers, etc which is likely the error you are experiencing.

This is a pretty common issue so I think I'll update the error message to explain this.

**Comment by romasilimcano** [comment]
Thanks. Using sam local it does create a APIGatewayProxyRequestEvent which has the httpMethod and headers. I do not know if I am missing out something, I have not tried servless for local testing so do not know if it is different.

**Comment by howardjohn** [comment]
Ok, I don't think SAM Local is the issue then.

Looking at the error again, it is coming from Jackson, which lambda uses internally to process json inputs. So it is trying to marshall it into a `ProxyRequest`. What should be happening is it turns it into an InputStream then this library uses Circe to turn it into a `ProxyRequest`. I think this is happening due to setting the wrong handler in Lambda. It should be [this function](https://github.com/howardjohn/scala-server-lambda/blob/master/common/src/main/scala/io/github/howardjohn/lambda/LambdaHandler.scala#L11) not [this function](https://github.com/howardjohn/scala-server-lambda/blob/master/http4s-lambda/src/main/scala/io/github/howardjohn/lambda/http4s/Http4sLambdaHandler.scala#L14), so it should look something like `<PACKAGE_NAME>.Route$EntryPoint::handle`. What handler are you using?

**Comment by romasilimcano** [comment]
Thanks a lot for you help. It did work with <handle> function, I was using handleRequest. But now I am running into a fs2 library issue,it  has nothing to do with this library but if you do not mind can you tell me what version of fs2 library you are using. For me it is downloading fs2-core_2.12_1.0.0.jar

java.lang.NoSuchMethodError: fs2.Stream$InvariantOps$.through$extension(Lfs2/internal/FreeC;Lscala/Function1;)Lfs2/internal/FreeC;
	at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.encodeBody(Http4sLambdaHandler.scala:63)
	at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.$anonfun$parseRequest$5(Http4sLambdaHandler.scala:53)
	at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.$anonfun$parseRequest$5$adapted(Http4sLambdaHandler.scala:53)
	at scala.Option.map(Option.scala:146)
	at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.$anonfun$parseRequest$2(Http4sLambdaHandler.scala:53)
	at scala.util.Either.map(Either.scala:350)
	at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.$anonfun$parseRequest$1(Http4sLambdaHandler.scala:47)
	at scala.util.Either.flatMap(Either.scala:338)
	at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.io$github$howardjohn$lambda$http4s$Http4sLambdaHandler$$parseRequest(Http4sLambdaHandler.scala:46)
	at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler.handleRequest(Http4sLambdaHandler.scala:15)
	at com.test.EntryPoint.handleRequest(Test.scala:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by howardjohn** [comment]
fs2 is pulled in from http4s. The fs2 version they use can be found at https://http4s.org/versions/.

If you use 0.3.1 of this library it uses http4s 18, which uses an older fs2. 0.4-SNAPSHOT uses the newer http4s 20.

**Comment by romasilimcano** [comment]
Thank you very much for all your help. And thanks for creating this fantastic library.
