### ISSUE TITLE
Update to http4s 20

### ISSUE THREAD

**Issue by howardjohn** [howardjohn/scala-server-lambda#5]

**Comment by rpiaggio** [comment]
Hi!

I'm getting:

```
org.http4s.Headers$.apply(Lscala/collection/immutable/List;)Lorg/http4s/Headers;: java.lang.NoSuchMethodError
java.lang.NoSuchMethodError: org.http4s.Headers$.apply(Lscala/collection/immutable/List;)Lorg/http4s/Headers;
at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.toHeaders(Http4sLambdaHandler.scala:58)
at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.$anonfun$parseRequest$3(Http4sLambdaHandler.scala:52)
at scala.Option.map(Option.scala:163)
at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.$anonfun$parseRequest$2(Http4sLambdaHandler.scala:52)
at scala.util.Either.map(Either.scala:353)
at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.$anonfun$parseRequest$1(Http4sLambdaHandler.scala:47)
at scala.util.Either.flatMap(Either.scala:341)
at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler$.io$github$howardjohn$lambda$http4s$Http4sLambdaHandler$$parseRequest(Http4sLambdaHandler.scala:46)
at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler.handleRequest(Http4sLambdaHandler.scala:15)
at io.github.howardjohn.lambda.LambdaHandler.handle(LambdaHandler.scala:17)
at io.github.howardjohn.lambda.LambdaHandler.handle$(LambdaHandler.scala:11)
at io.github.howardjohn.lambda.http4s.Http4sLambdaHandler.handle(Http4sLambdaHandler.scala:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
```

Is this because I'm using `http4s` `0.20`?

**Comment by howardjohn** [comment]
seems very likely

**Comment by howardjohn** [comment]
If you have a chance to try updating to version 20 a pull request would be appreciated, but I haven't had a chance to look into it at all
